docker buildx build --build-arg max_step_size=0.001 --build-arg physics_type=ode --tag lucasmrdt/sailboat-sim-lsa-gym:mss1-ode --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym  .
# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.002 --build-arg physics_type=ode --tag lucasmrdt/sailboat-sim-lsa-gym:mss2-ode --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .
# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.004 --build-arg physics_type=ode --tag lucasmrdt/sailboat-sim-lsa-gym:mss4-ode --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .

# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.001 --build-arg physics_type=bullet --tag lucasmrdt/sailboat-sim-lsa-gym:mss1-bullet --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .
# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.002 --build-arg physics_type=bullet --tag lucasmrdt/sailboat-sim-lsa-gym:mss2-bullet --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .
# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.004 --build-arg physics_type=bullet --tag lucasmrdt/sailboat-sim-lsa-gym:mss4-bullet --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .

# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.001 --build-arg physics_type=simbody --tag lucasmrdt/sailboat-sim-lsa-gym:mss1-simbody --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .
# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.002 --build-arg physics_type=simbody --tag lucasmrdt/sailboat-sim-lsa-gym:mss2-simbody --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .
# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.004 --build-arg physics_type=simbody --tag lucasmrdt/sailboat-sim-lsa-gym:mss4-simbody --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .

# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.001 --build-arg physics_type=dart --tag lucasmrdt/sailboat-sim-lsa-gym:mss1-dart --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .
# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.002 --build-arg physics_type=dart --tag lucasmrdt/sailboat-sim-lsa-gym:mss2-dart --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .
# docker buildx build --platform linux/amd64,linux/arm64/v8 --build-arg max_step_size=0.004 --build-arg physics_type=dart --tag lucasmrdt/sailboat-sim-lsa-gym:mss4-dart --cache-from type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --cache-to type=registry,ref=lucasmrdt/sailboat-sim-lsa-gym --push .